{
 "title": "Changement Climatique",
 "description": "Données relatives au changement climatique",
 "time": { "from": "1993-01-01T00:00:00.000Z", "to": "2023-01-01T00:00:00.000Z" },
 "panels": [
  { "title": "Indicateurs globaux", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "7) Émissions de GES par Habitant par Pays",
   "type": "geomap",
   "description": "Émissions de GES par habitant par pays (dernière mesure disponible)",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "masst" } }
  },
  {
   "title": "6) Part de la Superficie Forestière",
   "type": "geomap",
   "description": "Part de la superficie forestière (dernière mesure disponible)",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } }
  },
  {
   "title": "1) Concentration Atmosphérique de CO2",
   "type": "timeseries",
   "description": "Evolution de la concentration atmosphérique de CO2 entre 01-02-1958 et 01-04-2023",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ppm" } }
  },
  {
   "title": "5) Décompte des Catastrophes Naturelles par Type",
   "type": "stat",
   "description": "Décompte des catastrophes naturelles par type (dernière mesure disponible)",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } }
  },
  {
   "title": "3) Variation du Niveau Moyen de la Mer",
   "type": "timeseries",
   "description": "Changement du niveau moyen de la mer entre 01-11-1992 et 01-12-2022",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } }
  },
  { "title": "Indicateurs locaux (France)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "4) Émissions de GES en France",
   "type": "timeseries",
   "description": "Émissions de GES en france entre 01-12-1980 et 01-02-2020",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "masst" } }
  },
  {
   "title": "10) Catastrophe Naturelle la Plus Fréquente en France par Période de 5 ans en France",
   "type": "table",
   "description": "Catastrophe naturelle la plus fréquente en france par période de 5 ans en France entre 01-12-1979 et 01-02-2022",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } }
  },
  {
   "title": "9) Année Record de l'Augmentation de Température en France par Période de 5 ans",
   "type": "table",
   "description": "Année record de l'augmentation de température en France par période de 5 ans entre 01-12-1960 et 01-02-2022",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "celsius" } }
  },
  {
   "title": "2) Evolution de la Température de Surface en France",
   "type": "timeseries",
   "description": "Evolution de la température de surface en France entre 01-12-1960 et 01-02-2022 ",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "celsius" } }
  },
  {
   "title": "8) Décomposition de l'Occupation du Sol Français ",
   "type": "piechart",
   "description": "Décomposition de l'occupation du sol français (dernière mesure disponible)",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "hectares" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Notices & Droits d'Auteur",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 71 },
   "options": {
    "content": "Ce TP utilise les datasets [Climate Change Data](https://climatedata.imf.org/pages/climatechange-data) fourni par l'[IMF](https://imf.org/) et [CO2 and Greenhouse Gas Emissions](https://ourworldindata.org/co2-and-greenhouse-gas-emissions) fourni par [Our World In Data](https://ourworldindata.org/). Le dataset [CO2 and Greenhouse Gas Emissions](https://ourworldindata.org/co2-and-greenhouse-gas-emissions) est téléchargeable sur [GitHub](https://github.com/owid/co2-data)\n\nCopyright DWWM EPSI ONLINE"
   }
  }
 ]
}